# This playbook requires privilege escalation to be set. Please
# refer the ansible.cfg in current working directory for privilege_escalation
# configuration., ansibleS01

- name: Deploy a web application
  hosts: ansibleD00, ansibleD01, ansibleD02
  roles:
    - python
    - mysql_db
    - flask_web
